/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'zach_lysobey' at '4/13/15 3:30 PM' with Gradle 2.0
 *
 * @author zach_lysobey, @date 4/13/15 3:30 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
